# ============================================================================
# AI Coding Base Setup — Windows Installer/Updater (PowerShell)
# Configures Claude Code and opencode with shared MCPs, skills, hooks, plugins
#
# STATUS: STUB — Windows config paths need verification before full implementation
# TODO: Verify Claude Code desktop app config path on Windows
# TODO: Verify opencode desktop app config path on Windows
# ============================================================================

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClaudeDir = Join-Path $env:USERPROFILE ".claude"
$OpencodeDir = Join-Path $env:USERPROFILE ".config\opencode"  # TODO: verify
$SecretsDir = Join-Path $env:USERPROFILE ".aicodingsetup"
$SecretsFile = Join-Path $SecretsDir ".secrets.env"

Write-Host "============================================" -ForegroundColor Green
Write-Host " AI Coding Base Setup — Windows Installer" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""

# --- Prerequisite checks ---
$missing = @()
if (-not (Get-Command git -ErrorAction SilentlyContinue)) { $missing += "git" }
if (-not (Get-Command claude -ErrorAction SilentlyContinue)) { $missing += "claude (Claude Code CLI)" }

if ($missing.Count -gt 0) {
    Write-Host "ERROR: Missing required tools: $($missing -join ', ')" -ForegroundColor Red
    exit 1
}

# --- Secrets Management ---
if (-not (Test-Path $SecretsDir)) { New-Item -ItemType Directory -Path $SecretsDir -Force | Out-Null }

$requiredKeys = @(
    "FIRECRAWL_API_KEY",
    "BRAVE_API_KEY",
    "CLOUDFLARE_API_TOKEN",
    "CLOUDFLARE_ACCOUNT_ID",
    "LOGFIRE_TOKEN"
)

$secrets = @{}
if (Test-Path $SecretsFile) {
    Write-Host "INFO: Found existing secrets file" -ForegroundColor Blue
    Get-Content $SecretsFile | ForEach-Object {
        if ($_ -match '^([^#][^=]+)=(.*)$') {
            $secrets[$Matches[1]] = $Matches[2]
        }
    }
}

foreach ($key in $requiredKeys) {
    if (-not $secrets.ContainsKey($key) -or [string]::IsNullOrEmpty($secrets[$key])) {
        $value = Read-Host "Enter $key [or press Enter to skip]"
        $secrets[$key] = $value
    } else {
        Write-Host "  OK: $key already set" -ForegroundColor Green
    }
}

# Write secrets file
$secretsContent = "# AI Coding Base Setup - Secrets`n# Auto-generated by install.ps1`n"
foreach ($key in $requiredKeys) {
    $secretsContent += "$key=$($secrets[$key])`n"
}
Set-Content -Path $SecretsFile -Value $secretsContent

# --- Claude Code MCPs ---
Write-Host "`n=== Claude Code MCPs ===" -ForegroundColor Green

if ($secrets["FIRECRAWL_API_KEY"]) {
    & claude mcp add firecrawl -s user -e "FIRECRAWL_API_KEY=$($secrets['FIRECRAWL_API_KEY'])" -- firecrawl-mcp 2>$null
    Write-Host "  OK: firecrawl MCP configured" -ForegroundColor Green
}

if ($secrets["BRAVE_API_KEY"]) {
    & claude mcp add brave-search -s user -e "BRAVE_API_KEY=$($secrets['BRAVE_API_KEY'])" -- brave-search-mcp-server 2>$null
    Write-Host "  OK: brave-search MCP configured" -ForegroundColor Green
}

& claude mcp add context7 -s user -- docker run -i --rm context7-mcp 2>$null
Write-Host "  OK: context7 MCP configured" -ForegroundColor Green

& claude mcp add playwright -s user -- npx "@playwright/mcp@latest" --browser chromium 2>$null
Write-Host "  OK: playwright MCP configured" -ForegroundColor Green

# --- Claude Code Plugins ---
Write-Host "`n=== Claude Code Plugins ===" -ForegroundColor Green
$plugins = @(
    "superpowers@claude-plugins-official",
    "frontend-design@claude-plugins-official",
    "playwright@claude-plugins-official",
    "code-simplifier@claude-plugins-official",
    "skill-creator@claude-plugins-official",
    "code-review@claude-plugins-official",
    "claude-code-setup@claude-plugins-official",
    "pyright-lsp@claude-plugins-official"
)
foreach ($plugin in $plugins) {
    & claude plugin install $plugin 2>$null
    Write-Host "  OK: $plugin" -ForegroundColor Green
}

# --- Copy hooks and skills ---
Write-Host "`n=== Hooks & Skills ===" -ForegroundColor Green

# Statusline
$hooksDest = Join-Path $ClaudeDir "hooks"
if (-not (Test-Path $hooksDest)) { New-Item -ItemType Directory -Path $hooksDest -Force | Out-Null }
Copy-Item (Join-Path $ScriptDir "configs\claude\hooks\custom-statusline.js") (Join-Path $hooksDest "custom-statusline.js") -Force
Write-Host "  OK: custom-statusline.js installed" -ForegroundColor Green

# Skills
$skillsDest = Join-Path $ClaudeDir "skills"
Get-ChildItem (Join-Path $ScriptDir "skills") -Directory | ForEach-Object {
    $skillName = $_.Name
    $destDir = Join-Path $skillsDest $skillName
    if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
    $content = Get-Content (Join-Path $_.FullName "SKILL.md") -Raw
    foreach ($key in $requiredKeys) {
        $content = $content.Replace("{{$key}}", $secrets[$key])
    }
    Set-Content -Path (Join-Path $destDir "SKILL.md") -Value $content
    Write-Host "  OK: $skillName skill installed" -ForegroundColor Green
}

# --- TODO: settings.json merge, opencode config, bubblewrap ---
Write-Host "`nWARN: settings.json merge, opencode config, and bubblewrap symlink not yet implemented for Windows" -ForegroundColor Yellow
Write-Host "INFO: These require verifying Windows config paths first" -ForegroundColor Blue

Write-Host "`n=== Done! ===" -ForegroundColor Green
