#!/usr/bin/env bats

# ensure_lfs_autopull_safe: the universal images bake in the git-lfs feature's
# pull-git-lfs-artifacts.sh with AUTO_PULL=true hardcoded. That script runs
# `git lfs install` after install.sh and hard-fails `devcontainer up` when the
# workspace's pre-push hook is owned by another tool (e.g. pre-commit).
# install.sh must detect that case and flip AUTO_PULL=false; when the hooks are
# free it must leave the feature script alone.

setup() {
  : "${BLUEPRINT_ROOT:?unset — run via tests/bats/run.sh}"
  git lfs version &>/dev/null || skip "git-lfs not installed"
  TMPDIR=$(mktemp -d)
  export HOME="$TMPDIR"
  export AICODINGSETUP_SKIP_NETWORK=1
  export AICODINGSETUP_LFS_PULL_SCRIPT="$TMPDIR/pull-git-lfs-artifacts.sh"

  # Workspace repo the function operates on.
  REPO="$TMPDIR/workspace"
  mkdir -p "$REPO"
  (cd "$REPO" && git init -q)

  # Stand-in for the baked-in feature script (writable, so no sudo needed).
  cat > "$AICODINGSETUP_LFS_PULL_SCRIPT" <<'EOF'
#!/bin/sh
set -e
AUTO_PULL=true
git lfs install
git lfs pull
EOF
}

teardown() {
  rm -rf "$TMPDIR"
}

# Source install.sh (guards keep main/check_prerequisites from running) and
# invoke the function from inside the workspace repo, as postCreate would.
# _AICODINGSETUP_NVS_STRIPPED=1 skips the nvs-stripping self-reexec, which
# would otherwise run `bash "$0"` with $0 = the bash binary when sourced.
run_ensure() {
  run bash -c "cd '$REPO' && export _AICODINGSETUP_NVS_STRIPPED=1 && source '$BLUEPRINT_ROOT/install.sh' >/dev/null 2>&1; ensure_lfs_autopull_safe"
}

@test "foreign pre-push hook: AUTO_PULL flipped to false" {
  cat > "$REPO/.git/hooks/pre-push" <<'EOF'
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
exec pre-commit hook-impl "$@"
EOF
  chmod +x "$REPO/.git/hooks/pre-push"

  run_ensure
  [ "$status" -eq 0 ]
  grep -qx 'AUTO_PULL=false' "$AICODINGSETUP_LFS_PULL_SCRIPT"
  # The foreign hook must survive untouched.
  grep -q 'pre-commit hook-impl' "$REPO/.git/hooks/pre-push"
}

@test "free hooks: feature script left alone, lfs owns pre-push" {
  run_ensure
  [ "$status" -eq 0 ]
  grep -qx 'AUTO_PULL=true' "$AICODINGSETUP_LFS_PULL_SCRIPT"
  grep -q 'git lfs pre-push' "$REPO/.git/hooks/pre-push"
}

@test "no baked-in feature script: no-op" {
  rm "$AICODINGSETUP_LFS_PULL_SCRIPT"
  run_ensure
  [ "$status" -eq 0 ]
}

@test "not a git repo: feature script left alone" {
  rm -rf "$REPO/.git"
  run_ensure
  [ "$status" -eq 0 ]
  grep -qx 'AUTO_PULL=true' "$AICODINGSETUP_LFS_PULL_SCRIPT"
}
