# lib/provision-secrets.sh - interactive and non-interactive secrets setup
# for install.sh. Relies on install.sh globals and logging helpers; sourced
# only (no shebang / set -e), matching lib/*.sh.

# --- Secrets Management ---
load_or_prompt_secrets() {
  header "Secrets Management"
  mkdir -p "$SECRETS_DIR"

  local example_file="$SCRIPT_DIR/.secrets.env.example"
  if [[ ! -f "$example_file" ]]; then
    err "Missing .secrets.env.example in repo"
    exit 1
  fi

  # Parse required keys from example file
  local required_keys=()
  while IFS= read -r line; do
    # Skip comments and blank lines
    [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
    local key="${line%%=*}"
    required_keys+=("$key")
  done < "$example_file"

  # Load existing secrets if present
  declare -A secrets
  if [[ -f "$SECRETS_FILE" ]]; then
    info "Found existing secrets file"
    while IFS='=' read -r key value; do
      [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
      secrets["$key"]="$value"
    done < "$SECRETS_FILE"
  else
    info "No secrets file found — will prompt for all keys"
  fi

  # Decide whether we can prompt (no tty, container mode, or env opt-out → no)
  local can_prompt=true
  [[ ! -t 0 ]] && can_prompt=false
  [[ "$ENV_TYPE" == "container" ]] && can_prompt=false
  [[ "${AICODINGSETUP_NONINTERACTIVE:-}" == "1" ]] && can_prompt=false

  # Prompt for missing keys (keys with empty values are treated as "skipped", not missing)
  local prompted=false
  for key in "${required_keys[@]}"; do
    if [[ ! -v "secrets[$key]" ]]; then
      if [[ "$can_prompt" == "true" ]]; then
        prompted=true
        read -rp "Enter $key [or press Enter to skip]: " value
        secrets["$key"]="${value:-}"
      else
        info "$key not set (non-interactive — leaving empty)"
        secrets["$key"]=""
      fi
    else
      if [[ -n "${secrets[$key]}" ]]; then
        ok "$key already set"
      else
        ok "$key skipped (empty)"
      fi
    fi
  done

  # Write secrets file — but NEVER regenerate an existing one in non-interactive
  # mode. ~/.aicodingsetup/.secrets.env is typically a host bind mount: the single
  # source of truth shared across containers. A container can't prompt, so a
  # rewrite would stamp every key it lacks (e.g. a freshly-added GH_TOKEN) to
  # EMPTY — destroying the user's real tokens on the host. So: only (re)write when
  # we can prompt (interactive host setup) or when bootstrapping a missing file.
  # When an existing file is left untouched, values already loaded above are still
  # exported below for secret substitution.
  if [[ -f "$SECRETS_FILE" && "$can_prompt" != "true" ]]; then
    info "Existing secrets file left untouched (non-interactive — host file is authoritative)"
  else
    {
      echo "# AI Coding Base Setup — Secrets"
      echo "# Auto-generated by install.sh — do not commit"
      echo ""
      for key in "${required_keys[@]}"; do
        echo "${key}=${secrets[$key]:-}"
      done
    } > "$SECRETS_FILE"
    chmod 600 "$SECRETS_FILE"
  fi

  if [[ "$prompted" == "true" ]]; then
    ok "Secrets saved to $SECRETS_FILE"
  fi

  # Export secrets for use by other functions
  for key in "${required_keys[@]}"; do
    export "$key"="${secrets[$key]:-}"
  done
}
